imports:
    - { resource: doctrine.yml }
    - { resource: security.yml }
    - { resource: fos/rest.yml }
    - { resource: fos/user.yml }
    - { resource: fos/http_cache.yml }
    - { resource: fos/oauth_server.yml }
    - { resource: knp/gaufrette.yml }
    - { resource: jms/serializer.yml }
    - { resource: stof/doctrine_extensions.yml }
    - { resource: variable/variable.yml }

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport:        "%mailer_transport%"
    host:             "%mailer_host%"
    username:         "%mailer_user%"
    password:         "%mailer_password%"
    spool:            "%mailer_spool%"
    delivery_address: "%mailer_delivery_address%"

sensio_framework_extra:
    view:    { annotations: false }
    request: { converters: true }
    router:  { annotations: true }
    security:    { annotations: true }

nelmio_api_doc:
    #exclude_sections: [internal]
    #cache:
    #    enabled: true
    swagger:
        api_base_path: /api
    sandbox:
        authentication:
            delivery: http
            type:     bearer
        body_format:
            formats:
                - json
        request_format:
            formats:
                json: application/json
            default_format: json

seven_tag_app:
    plugins_dir:
        - '%kernel.root_dir%/../src/SevenTag/Plugin'
    updater:
        auto_republish: true

seven_tag_container:
    search_engine: orm

liip_monitor:
    checks:
        writable_directory:
            - "%kernel.cache_dir%"
            - "%kernel.logs_dir%"
        symfony_requirements:
            file: '%kernel.root_dir%/../var/SymfonyRequirements.php'
