Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true
  config.vm.network "private_network", ip: "100.0.0.210"
  config.vm.synced_folder "../", "/var/www/7tag", type: "nfs", nfs_udp: false, nfs_export: true

  config.vm.provider "virtualbox" do |v|
    v.name = "7tag-vagrant"
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "\n" >> .bashrc
    echo "alias reload-docker-configuration='docker-compose stop && docker-compose build && docker-compose up -d'" >> .bashrc
    echo "\n" >> .bashrc
  SHELL
end
