#!/usr/bin/env php
<?php
/**
 * Copyright (C) 2015 Digimedia Sp. z o.o. d/b/a Clearcode
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

require __DIR__.'/../vendor/autoload.php';

$directories = array(
    __DIR__.'/../app/DoctrineMigrations',
    __DIR__.'/../src',
    __DIR__.'/../behat'
);

$finder = new \Symfony\Component\Finder\Finder();
$finder->files()->in($directories)->name('*.php');

$license = <<<EOT
<?php
/**
 * Copyright (C) 2015 Digimedia Sp. z o.o. d/b/a Clearcode
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
EOT;

$filesWithoutLicense = [];
/** @var \Symfony\Component\Finder\SplFileInfo $file */
foreach($finder as $file) {
    if($license !== substr($file->getContents(), 0, strlen($license))) {
        $filesWithoutLicense[] = $file->getRealPath();
    }
}

if(!empty($filesWithoutLicense)) {
    printf("Files without license information have been found:\n\n%s.", implode("\n", $filesWithoutLicense));
    exit(1);
}