SevenTag\Api\TriggerBundle\Entity\Trigger:
  type: entity
  table: `trigger`
  repositoryClass: SevenTag\Api\TriggerBundle\Entity\TriggerRepository
  indexes:
    triggerUpdatedAt:
      columns: [updatedAt]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    type:
      type: integer
    strategy:
      type: integer
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    container:
      targetEntity: SevenTag\Api\ContainerBundle\Entity\Container
      inversedBy: triggers
      joinColumn:
        name: container_id
        referencedColumnName: id
        onDelete: CASCADE
        onUpdate: CASCADE
  oneToMany:
    conditions:
      targetEntity: SevenTag\Api\TriggerBundle\Entity\Condition
      mappedBy: trigger
      cascade: ['all']
      orphanRemoval: true
  manyToMany:
    tags:
      targetEntity: SevenTag\Api\TagBundle\Entity\Tag
      mappedBy: triggers